// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: s4A8zbVV2YneJHZ4PPAS7d
// Component: AHVBnXmex-jZ

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  usePlasmicDataConfig,
  executePlasmicDataOp,
  useDependencyAwareQuery
} from "@plasmicapp/react-web/lib/data-sources";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import IconLabel from "../../IconLabel"; // plasmic-import: 76wng9QPPi/component
import { AntdMenu } from "@plasmicpkgs/antd5/skinny/registerMenu"; // plasmic-import: fo-n3xHvdqt/codeComponent
import { AntdMenuItem } from "@plasmicpkgs/antd5/skinny/registerMenu"; // plasmic-import: QSmezaW-Gyu/codeComponent
import CardItem from "../../CardItem"; // plasmic-import: 3Xy4dZ9QFi/component
import { RichTable } from "@plasmicpkgs/plasmic-rich-components"; // plasmic-import: k4RvFQUTZKCU/codeComponent
import { tableHelpers as RichTable_Helpers } from "@plasmicpkgs/plasmic-rich-components"; // plasmic-import: k4RvFQUTZKCU/codeComponentHelper
import TripView from "../../TripView"; // plasmic-import: ibDSAEBazH/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources"; // plasmic-import: eqBx5aJsUvSBW/codeComponent

import { useScreenVariants as useScreenVariantsn3GbfBwefkZu8 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: n3gbfBWEFKZu8/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_ovni.module.css"; // plasmic-import: s4A8zbVV2YneJHZ4PPAS7d/projectcss
import sty from "./PlasmicExcursao.module.css"; // plasmic-import: AHVBnXmex-jZ/css

import LocalActivitysvgIcon from "./icons/PlasmicIcon__LocalActivitysvg"; // plasmic-import: 9Ti-YtqDJa/icon
import EventSeatsvgIcon from "./icons/PlasmicIcon__EventSeatsvg"; // plasmic-import: nUclHWRbUL/icon
import PaymentsFill0Wght400Grad0Opsz48SvgIcon from "./icons/PlasmicIcon__PaymentsFill0Wght400Grad0Opsz48Svg"; // plasmic-import: sB3rP83jcG/icon
import CalculatesvgIcon from "./icons/PlasmicIcon__Calculatesvg"; // plasmic-import: CcAtW2QgHs/icon
import FinanceChipsvgIcon from "./icons/PlasmicIcon__FinanceChipsvg"; // plasmic-import: bdbiJ_6oxU/icon
import ModeOfTravelsvgIcon from "./icons/PlasmicIcon__ModeOfTravelsvg"; // plasmic-import: WZEm74zGD5/icon

export type PlasmicExcursao__VariantMembers = {};
export type PlasmicExcursao__VariantsArgs = {};
type VariantPropType = keyof PlasmicExcursao__VariantsArgs;
export const PlasmicExcursao__VariantProps = new Array<VariantPropType>();

export type PlasmicExcursao__ArgsType = {
  actriveView?: string;
  onActriveViewChange?: (val: string) => void;
};
type ArgPropType = keyof PlasmicExcursao__ArgsType;
export const PlasmicExcursao__ArgProps = new Array<ArgPropType>(
  "actriveView",
  "onActriveViewChange"
);

export type PlasmicExcursao__OverridesType = {
  root?: p.Flex<"div">;
  tumbnail?: p.Flex<typeof p.PlasmicImg>;
  header?: p.Flex<"div">;
  left?: p.Flex<"div">;
  caption?: p.Flex<"div">;
  title?: p.Flex<"h2">;
  subtitle?: p.Flex<"h3">;
  date?: p.Flex<"div">;
  right?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  info1?: p.Flex<"div">;
  soldTickets?: p.Flex<typeof IconLabel>;
  label?: p.Flex<"div">;
  emptySeats?: p.Flex<typeof IconLabel>;
  label2?: p.Flex<"div">;
  info2?: p.Flex<"div">;
  revenue?: p.Flex<typeof IconLabel>;
  label3?: p.Flex<"div">;
  averagePrice?: p.Flex<typeof IconLabel>;
  label4?: p.Flex<"div">;
  menu?: p.Flex<typeof AntdMenu>;
  salesTab?: p.Flex<typeof AntdMenuItem>;
  tabButton1?: p.Flex<"div">;
  text?: p.Flex<"div">;
  tripsTab?: p.Flex<typeof AntdMenuItem>;
  tabButton2?: p.Flex<"div">;
  viagens?: p.Flex<"div">;
  body?: p.Flex<"section">;
  salesView?: p.Flex<"div">;
  batches?: p.Flex<"div">;
  batchesHeading?: p.Flex<"div">;
  batchesTitle?: p.Flex<"h3">;
  batchItem?: p.Flex<typeof CardItem>;
  orders?: p.Flex<"div">;
  ordersHeading?: p.Flex<"div">;
  ordersTitle?: p.Flex<"h3">;
  ordersTable?: p.Flex<typeof RichTable>;
  tripView?: p.Flex<typeof TripView>;
};

export interface DefaultExcursaoProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicExcursao__RenderFunc(props: {
  variants: PlasmicExcursao__VariantsArgs;
  args: PlasmicExcursao__ArgsType;
  overrides: PlasmicExcursao__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "actriveView",
        type: "writable",
        variableType: "text",

        valueProp: "actriveView",
        onChangeProp: "onActriveViewChange"
      },
      {
        path: "ordersTable.selectedRowKey",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "ordersTable.selectedRow",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "ordersTable.selectedRows",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],
    [$props, $ctx]
  );
  const $state = p.useDollarState(stateSpecs, { $props, $ctx, $queries });

  useDependencyAwareQuery({
    name: "tour",
    getDataOp: () => ({
      sourceId: "bZTAeS7zkVosmEWwykBedp",
      opId: "1a02d92e-a612-44f0-8f11-92c44ab10952",
      userArgs: {
        params: [
          (() => {
            try {
              return $ctx.query.tour_id;
            } catch (e) {
              if (e instanceof TypeError) {
                return null;
              }
              throw e;
            }
          })()
        ]
      },
      cacheKey:
        "plasmic.$." +
        (() => {
          try {
            return "tour_detail";
          } catch (e) {
            if (e instanceof TypeError) {
              return "";
            }
            throw e;
          }
        })() +
        ".$.KuPiQuxZx.$.",
      invalidatedKeys: null,
      roleId: null
    }),
    $queries,
    setDollarQueries
  });
  useDependencyAwareQuery({
    name: "orders",
    getDataOp: () => ({
      sourceId: "3D2qpwXrTDzp5gVoPy8prT",
      opId: "95a3832c-ee66-4324-ae10-9ab67bb0b4d0",
      userArgs: {
        filters: [
          (() => {
            try {
              return $queries.tour.data.response.title;
            } catch (e) {
              if (e instanceof TypeError) {
                return null;
              }
              throw e;
            }
          })()
        ]
      },
      cacheKey: "plasmic.$.IvRvzteX7.$.",
      invalidatedKeys: null,
      roleId: null
    }),
    $queries,
    setDollarQueries
  });
  useDependencyAwareQuery({
    name: "trips",
    getDataOp: () => ({
      sourceId: "3D2qpwXrTDzp5gVoPy8prT",
      opId: "58ac1a18-f52e-4225-9eb0-5a483dba68a4",
      userArgs: {
        filters: [
          (() => {
            try {
              return $queries.tour.data.response.title;
            } catch (e) {
              if (e instanceof TypeError) {
                return null;
              }
              throw e;
            }
          })()
        ]
      },
      cacheKey: "plasmic.$.VO3GXtcgk.$.",
      invalidatedKeys: null,
      roleId: null
    }),
    $queries,
    setDollarQueries
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsn3GbfBwefkZu8()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicExcursao.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicExcursao.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicExcursao.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          {true ? (
            <p.PlasmicImg
              data-plasmic-name={"tumbnail"}
              data-plasmic-override={overrides.tumbnail}
              alt={""}
              className={classNames(sty.tumbnail)}
              displayHeight={
                hasVariant(globalVariants, "screen", "sm")
                  ? ("300px" as const)
                  : ("600px" as const)
              }
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"100%" as const}
              loading={"lazy" as const}
              src={(() => {
                try {
                  return $queries.tour.data.response.tumbnail[0].url;
                } catch (e) {
                  if (e instanceof TypeError) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
            />
          ) : null}
          {(hasVariant(globalVariants, "screen", "sm") ? true : true) ? (
            <p.Stack
              as={"div"}
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              hasGap={true}
              className={classNames(projectcss.all, sty.header)}
            >
              {(hasVariant(globalVariants, "screen", "sm") ? true : true) ? (
                <div
                  data-plasmic-name={"left"}
                  data-plasmic-override={overrides.left}
                  className={classNames(projectcss.all, sty.left)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"caption"}
                    data-plasmic-override={overrides.caption}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.caption)}
                  >
                    <h2
                      data-plasmic-name={"title"}
                      data-plasmic-override={overrides.title}
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.title
                      )}
                    >
                      {(() => {
                        try {
                          return $queries.tour.data.response.title;
                        } catch (e) {
                          if (e instanceof TypeError) {
                            return "Enter some text";
                          }
                          throw e;
                        }
                      })()}
                    </h2>
                    <h3
                      data-plasmic-name={"subtitle"}
                      data-plasmic-override={overrides.subtitle}
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.subtitle
                      )}
                    >
                      {(() => {
                        try {
                          return $queries.tour.data.response.subtitle;
                        } catch (e) {
                          if (e instanceof TypeError) {
                            return "Enter some text";
                          }
                          throw e;
                        }
                      })()}
                    </h3>
                  </p.Stack>
                  <div
                    data-plasmic-name={"date"}
                    data-plasmic-override={overrides.date}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.date
                    )}
                  >
                    {(() => {
                      try {
                        return $queries.tour.data.response.datetime[0];
                      } catch (e) {
                        if (e instanceof TypeError) {
                          return "Enter some text";
                        }
                        throw e;
                      }
                    })()}
                  </div>
                </div>
              ) : null}
              {(hasVariant(globalVariants, "screen", "sm") ? true : true) ? (
                <div
                  data-plasmic-name={"right"}
                  data-plasmic-override={overrides.right}
                  className={classNames(projectcss.all, sty.right)}
                >
                  {true ? (
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"freeBox"}
                      data-plasmic-override={overrides.freeBox}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox)}
                    >
                      {true ? (
                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"info1"}
                          data-plasmic-override={overrides.info1}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.info1)}
                        >
                          <IconLabel
                            data-plasmic-name={"soldTickets"}
                            data-plasmic-override={overrides.soldTickets}
                            className={classNames(
                              "__wab_instance",
                              sty.soldTickets
                            )}
                            icon={
                              <LocalActivitysvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__bsarG
                                )}
                                role={"img"}
                              />
                            }
                          >
                            <div
                              data-plasmic-name={"label"}
                              data-plasmic-override={overrides.label}
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.label
                              )}
                            >
                              {(() => {
                                try {
                                  return (
                                    $queries.tour.data.response.occupancy +
                                    " passagens"
                                  );
                                } catch (e) {
                                  if (e instanceof TypeError) {
                                    return "Label";
                                  }
                                  throw e;
                                }
                              })()}
                            </div>
                          </IconLabel>
                          <IconLabel
                            data-plasmic-name={"emptySeats"}
                            data-plasmic-override={overrides.emptySeats}
                            className={classNames(
                              "__wab_instance",
                              sty.emptySeats
                            )}
                            icon={
                              <EventSeatsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__gZAuL
                                )}
                                role={"img"}
                              />
                            }
                          >
                            <div
                              data-plasmic-name={"label2"}
                              data-plasmic-override={overrides.label2}
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.label2
                              )}
                            >
                              {(() => {
                                try {
                                  return (
                                    $queries.tour.data.response.avaiability +
                                    " vagas"
                                  );
                                } catch (e) {
                                  if (e instanceof TypeError) {
                                    return "Label";
                                  }
                                  throw e;
                                }
                              })()}
                            </div>
                          </IconLabel>
                        </p.Stack>
                      ) : null}
                      {true ? (
                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"info2"}
                          data-plasmic-override={overrides.info2}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.info2)}
                        >
                          <IconLabel
                            data-plasmic-name={"revenue"}
                            data-plasmic-override={overrides.revenue}
                            className={classNames(
                              "__wab_instance",
                              sty.revenue
                            )}
                            icon={
                              <PaymentsFill0Wght400Grad0Opsz48SvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__y0Qi8
                                )}
                                role={"img"}
                              />
                            }
                          >
                            <div
                              data-plasmic-name={"label3"}
                              data-plasmic-override={overrides.label3}
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.label3
                              )}
                            >
                              {(() => {
                                try {
                                  return (
                                    "R$ " + $queries.tour.data.response.revenue
                                  );
                                } catch (e) {
                                  if (e instanceof TypeError) {
                                    return "Label";
                                  }
                                  throw e;
                                }
                              })()}
                            </div>
                          </IconLabel>
                          <IconLabel
                            data-plasmic-name={"averagePrice"}
                            data-plasmic-override={overrides.averagePrice}
                            className={classNames(
                              "__wab_instance",
                              sty.averagePrice
                            )}
                            icon={
                              <CalculatesvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__z63Ra
                                )}
                                role={"img"}
                              />
                            }
                          >
                            <div
                              data-plasmic-name={"label4"}
                              data-plasmic-override={overrides.label4}
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.label4
                              )}
                            >
                              {(() => {
                                try {
                                  return (
                                    "R$ " +
                                    $queries.tour.data.response.average_price
                                  );
                                } catch (e) {
                                  if (e instanceof TypeError) {
                                    return "Label";
                                  }
                                  throw e;
                                }
                              })()}
                            </div>
                          </IconLabel>
                        </p.Stack>
                      ) : null}
                    </p.Stack>
                  ) : null}
                </div>
              ) : null}
            </p.Stack>
          ) : null}
          <AntdMenu
            data-plasmic-name={"menu"}
            data-plasmic-override={overrides.menu}
            className={classNames("__wab_instance", sty.menu)}
            multiple={false}
            triggerSubMenuAction={"click" as const}
          >
            <AntdMenuItem
              data-plasmic-name={"salesTab"}
              data-plasmic-override={overrides.salesTab}
              className={classNames("__wab_instance", sty.salesTab)}
              key={"sales" as const}
              onClick={async () => {
                const $steps = {};
                $steps["updateActriveView"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "GVgqYQrdQ",
                            componentUuid: "AHVBnXmex-jZ",
                            argName: "variable"
                          },
                          () => ({
                            objRoot: $state,
                            variablePath: ["actriveView"]
                          })
                        ),
                        operation: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "GVgqYQrdQ",
                            componentUuid: "AHVBnXmex-jZ",
                            argName: "operation"
                          },
                          () => 0
                        ),
                        value: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "GVgqYQrdQ",
                            componentUuid: "AHVBnXmex-jZ",
                            argName: "value"
                          },
                          () => "sales"
                        )
                      };
                      return __wrapUserFunction(
                        {
                          type: "InteractionLoc",
                          actionName: "updateVariable",
                          interactionUuid: "GVgqYQrdQ",
                          componentUuid: "AHVBnXmex-jZ"
                        },
                        () =>
                          (({ variable, value, startIndex, deleteCount }) => {
                            const { objRoot, variablePath } = variable;

                            p.set(objRoot, variablePath, value);
                            return value;
                          })?.apply(null, [actionArgs]),
                        actionArgs
                      );
                    })()
                  : undefined;
                if (
                  typeof $steps["updateActriveView"] === "object" &&
                  typeof $steps["updateActriveView"].then === "function"
                ) {
                  $steps["updateActriveView"] = await __wrapUserPromise(
                    {
                      type: "InteractionLoc",
                      actionName: "updateVariable",
                      interactionUuid: "GVgqYQrdQ",
                      componentUuid: "AHVBnXmex-jZ"
                    },
                    $steps["updateActriveView"]
                  );
                }
              }}
              title={"sales" as const}
            >
              {true ? (
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"tabButton1"}
                  data-plasmic-override={overrides.tabButton1}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.tabButton1)}
                >
                  <FinanceChipsvgIcon
                    className={classNames(projectcss.all, sty.svg__mlLUo)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"text"}
                    data-plasmic-override={overrides.text}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text
                    )}
                  >
                    {"Vendas"}
                  </div>
                </p.Stack>
              ) : null}
            </AntdMenuItem>
            <AntdMenuItem
              data-plasmic-name={"tripsTab"}
              data-plasmic-override={overrides.tripsTab}
              className={classNames("__wab_instance", sty.tripsTab)}
              key={"trips" as const}
              onClick={async () => {
                const $steps = {};
                $steps["updateActriveView"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "G8MNL87Ul",
                            componentUuid: "AHVBnXmex-jZ",
                            argName: "variable"
                          },
                          () => ({
                            objRoot: $state,
                            variablePath: ["actriveView"]
                          })
                        ),
                        operation: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "G8MNL87Ul",
                            componentUuid: "AHVBnXmex-jZ",
                            argName: "operation"
                          },
                          () => 0
                        ),
                        value: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "G8MNL87Ul",
                            componentUuid: "AHVBnXmex-jZ",
                            argName: "value"
                          },
                          () => "trips"
                        )
                      };
                      return __wrapUserFunction(
                        {
                          type: "InteractionLoc",
                          actionName: "updateVariable",
                          interactionUuid: "G8MNL87Ul",
                          componentUuid: "AHVBnXmex-jZ"
                        },
                        () =>
                          (({ variable, value, startIndex, deleteCount }) => {
                            const { objRoot, variablePath } = variable;

                            p.set(objRoot, variablePath, value);
                            return value;
                          })?.apply(null, [actionArgs]),
                        actionArgs
                      );
                    })()
                  : undefined;
                if (
                  typeof $steps["updateActriveView"] === "object" &&
                  typeof $steps["updateActriveView"].then === "function"
                ) {
                  $steps["updateActriveView"] = await __wrapUserPromise(
                    {
                      type: "InteractionLoc",
                      actionName: "updateVariable",
                      interactionUuid: "G8MNL87Ul",
                      componentUuid: "AHVBnXmex-jZ"
                    },
                    $steps["updateActriveView"]
                  );
                }
              }}
              title={"trips" as const}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"tabButton2"}
                data-plasmic-override={overrides.tabButton2}
                hasGap={true}
                className={classNames(projectcss.all, sty.tabButton2)}
              >
                <ModeOfTravelsvgIcon
                  className={classNames(projectcss.all, sty.svg__qwsmA)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"viagens"}
                  data-plasmic-override={overrides.viagens}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.viagens
                  )}
                >
                  {"Viagens"}
                </div>
              </p.Stack>
            </AntdMenuItem>
          </AntdMenu>
          {true ? (
            <section
              data-plasmic-name={"body"}
              data-plasmic-override={overrides.body}
              className={classNames(projectcss.all, sty.body)}
            >
              {(() => {
                try {
                  return $state.actriveView == "sales";
                } catch (e) {
                  if (e instanceof TypeError) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"salesView"}
                  data-plasmic-override={overrides.salesView}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.salesView)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"batches"}
                    data-plasmic-override={overrides.batches}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.batches)}
                  >
                    {true ? (
                      <div
                        data-plasmic-name={"batchesHeading"}
                        data-plasmic-override={overrides.batchesHeading}
                        className={classNames(
                          projectcss.all,
                          sty.batchesHeading
                        )}
                      >
                        <h3
                          data-plasmic-name={"batchesTitle"}
                          data-plasmic-override={overrides.batchesTitle}
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.batchesTitle
                          )}
                        >
                          {"Ofertas"}
                        </h3>
                      </div>
                    ) : null}
                    {(
                      (() => {
                        try {
                          return $queries.tour.data.response.batches;
                        } catch (e) {
                          if (e instanceof TypeError) {
                            return [];
                          }
                          throw e;
                        }
                      })() ?? []
                    ).map((batch, currentIndex) => (
                      <CardItem
                        data-plasmic-name={"batchItem"}
                        data-plasmic-override={overrides.batchItem}
                        className={classNames("__wab_instance", sty.batchItem)}
                        description={batch.description}
                        highlight={batch.sold + " pedidos"}
                        key={currentIndex}
                        title={batch.title}
                      />
                    ))}
                  </p.Stack>
                  {(
                    hasVariant(globalVariants, "screen", "sm") ? true : true
                  ) ? (
                    <div
                      data-plasmic-name={"orders"}
                      data-plasmic-override={overrides.orders}
                      className={classNames(projectcss.all, sty.orders)}
                    >
                      {true ? (
                        <div
                          data-plasmic-name={"ordersHeading"}
                          data-plasmic-override={overrides.ordersHeading}
                          className={classNames(
                            projectcss.all,
                            sty.ordersHeading
                          )}
                        >
                          <h3
                            data-plasmic-name={"ordersTitle"}
                            data-plasmic-override={overrides.ordersTitle}
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.ordersTitle
                            )}
                          >
                            {"Pedidos"}
                          </h3>
                        </div>
                      ) : null}
                      {(() => {
                        const child$Props = {
                          className: classNames(
                            "__wab_instance",
                            sty.ordersTable
                          ),
                          data: (() => {
                            try {
                              return $queries.tour.data.response.orders;
                            } catch (e) {
                              if (e instanceof TypeError) {
                                return undefined;
                              }
                              throw e;
                            }
                          })(),
                          fields: (() => {
                            const __composite = [
                              {
                                key: "tickets",
                                fieldId: "tickets",
                                isHidden: true
                              },
                              {
                                key: "batch",
                                fieldId: "batch",
                                isHidden: true
                              },
                              { key: "id", fieldId: "id", isHidden: true },
                              { key: "user", fieldId: "user", isHidden: true },
                              {
                                key: "formatted_datetime",
                                fieldId: "formatted_datetime",
                                title: "Data"
                              },
                              {
                                key: "buyer_name",
                                fieldId: "buyer_name",
                                title: "Comprador"
                              },
                              {
                                key: "ticket_count",
                                fieldId: "ticket_count",
                                title: "Passagens"
                              },
                              {
                                key: "total",
                                fieldId: "total",
                                title: "Total",
                                expr: null
                              },
                              {
                                key: "status",
                                fieldId: "status",
                                title: "Status"
                              },
                              { key: "tour", fieldId: "tour", isHidden: true },
                              {
                                key: "passengers",
                                fieldId: "passengers",
                                isHidden: true
                              },
                              {
                                key: "record_id",
                                fieldId: "record_id",
                                isHidden: true
                              },
                              {
                                key: "datetime",
                                fieldId: "datetime",
                                isHidden: true
                              }
                            ];
                            __composite["7"]["expr"] = currentItem => {
                              return "R$ " + currentItem.total;
                            };
                            return __composite;
                          })(),

                          onRowSelectionChanged: async (...eventArgs) => {
                            p.generateStateOnChangePropForCodeComponents(
                              $state,
                              "selectedRowKey",
                              ["ordersTable", "selectedRowKey"],
                              RichTable_Helpers
                            ).apply(null, eventArgs);
                            p.generateStateOnChangePropForCodeComponents(
                              $state,
                              "selectedRow",
                              ["ordersTable", "selectedRow"],
                              RichTable_Helpers
                            ).apply(null, eventArgs);
                            p.generateStateOnChangePropForCodeComponents(
                              $state,
                              "selectedRows",
                              ["ordersTable", "selectedRows"],
                              RichTable_Helpers
                            ).apply(null, eventArgs);
                          },
                          selectedRowKey: p.generateStateValueProp($state, [
                            "ordersTable",
                            "selectedRowKey"
                          ])
                        };
                        p.initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "selectedRowKey",
                              plasmicStateName: "ordersTable.selectedRowKey"
                            },
                            {
                              name: "selectedRow",
                              plasmicStateName: "ordersTable.selectedRow"
                            },
                            {
                              name: "selectedRows",
                              plasmicStateName: "ordersTable.selectedRows"
                            }
                          ],
                          [],
                          RichTable_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <RichTable
                            data-plasmic-name={"ordersTable"}
                            data-plasmic-override={overrides.ordersTable}
                            {...child$Props}
                          />
                        );
                      })()}
                    </div>
                  ) : null}
                </p.Stack>
              ) : null}
              {(() => {
                try {
                  return $state.actriveView == "trips";
                } catch (e) {
                  if (e instanceof TypeError) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <TripView
                  data-plasmic-name={"tripView"}
                  data-plasmic-override={overrides.tripView}
                  className={classNames("__wab_instance", sty.tripView)}
                  tourTitle={$queries.tour.data.response.title}
                />
              ) : null}
            </section>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "tumbnail",
    "header",
    "left",
    "caption",
    "title",
    "subtitle",
    "date",
    "right",
    "freeBox",
    "info1",
    "soldTickets",
    "label",
    "emptySeats",
    "label2",
    "info2",
    "revenue",
    "label3",
    "averagePrice",
    "label4",
    "menu",
    "salesTab",
    "tabButton1",
    "text",
    "tripsTab",
    "tabButton2",
    "viagens",
    "body",
    "salesView",
    "batches",
    "batchesHeading",
    "batchesTitle",
    "batchItem",
    "orders",
    "ordersHeading",
    "ordersTitle",
    "ordersTable",
    "tripView"
  ],
  tumbnail: ["tumbnail"],
  header: [
    "header",
    "left",
    "caption",
    "title",
    "subtitle",
    "date",
    "right",
    "freeBox",
    "info1",
    "soldTickets",
    "label",
    "emptySeats",
    "label2",
    "info2",
    "revenue",
    "label3",
    "averagePrice",
    "label4"
  ],
  left: ["left", "caption", "title", "subtitle", "date"],
  caption: ["caption", "title", "subtitle"],
  title: ["title"],
  subtitle: ["subtitle"],
  date: ["date"],
  right: [
    "right",
    "freeBox",
    "info1",
    "soldTickets",
    "label",
    "emptySeats",
    "label2",
    "info2",
    "revenue",
    "label3",
    "averagePrice",
    "label4"
  ],
  freeBox: [
    "freeBox",
    "info1",
    "soldTickets",
    "label",
    "emptySeats",
    "label2",
    "info2",
    "revenue",
    "label3",
    "averagePrice",
    "label4"
  ],
  info1: ["info1", "soldTickets", "label", "emptySeats", "label2"],
  soldTickets: ["soldTickets", "label"],
  label: ["label"],
  emptySeats: ["emptySeats", "label2"],
  label2: ["label2"],
  info2: ["info2", "revenue", "label3", "averagePrice", "label4"],
  revenue: ["revenue", "label3"],
  label3: ["label3"],
  averagePrice: ["averagePrice", "label4"],
  label4: ["label4"],
  menu: [
    "menu",
    "salesTab",
    "tabButton1",
    "text",
    "tripsTab",
    "tabButton2",
    "viagens"
  ],
  salesTab: ["salesTab", "tabButton1", "text"],
  tabButton1: ["tabButton1", "text"],
  text: ["text"],
  tripsTab: ["tripsTab", "tabButton2", "viagens"],
  tabButton2: ["tabButton2", "viagens"],
  viagens: ["viagens"],
  body: [
    "body",
    "salesView",
    "batches",
    "batchesHeading",
    "batchesTitle",
    "batchItem",
    "orders",
    "ordersHeading",
    "ordersTitle",
    "ordersTable",
    "tripView"
  ],
  salesView: [
    "salesView",
    "batches",
    "batchesHeading",
    "batchesTitle",
    "batchItem",
    "orders",
    "ordersHeading",
    "ordersTitle",
    "ordersTable"
  ],
  batches: ["batches", "batchesHeading", "batchesTitle", "batchItem"],
  batchesHeading: ["batchesHeading", "batchesTitle"],
  batchesTitle: ["batchesTitle"],
  batchItem: ["batchItem"],
  orders: ["orders", "ordersHeading", "ordersTitle", "ordersTable"],
  ordersHeading: ["ordersHeading", "ordersTitle"],
  ordersTitle: ["ordersTitle"],
  ordersTable: ["ordersTable"],
  tripView: ["tripView"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  tumbnail: typeof p.PlasmicImg;
  header: "div";
  left: "div";
  caption: "div";
  title: "h2";
  subtitle: "h3";
  date: "div";
  right: "div";
  freeBox: "div";
  info1: "div";
  soldTickets: typeof IconLabel;
  label: "div";
  emptySeats: typeof IconLabel;
  label2: "div";
  info2: "div";
  revenue: typeof IconLabel;
  label3: "div";
  averagePrice: typeof IconLabel;
  label4: "div";
  menu: typeof AntdMenu;
  salesTab: typeof AntdMenuItem;
  tabButton1: "div";
  text: "div";
  tripsTab: typeof AntdMenuItem;
  tabButton2: "div";
  viagens: "div";
  body: "section";
  salesView: "div";
  batches: "div";
  batchesHeading: "div";
  batchesTitle: "h3";
  batchItem: typeof CardItem;
  orders: "div";
  ordersHeading: "div";
  ordersTitle: "h3";
  ordersTable: typeof RichTable;
  tripView: typeof TripView;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicExcursao__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicExcursao__VariantsArgs;
    args?: PlasmicExcursao__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicExcursao__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicExcursao__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicExcursao__ArgProps,
          internalVariantPropNames: PlasmicExcursao__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicExcursao__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicExcursao";
  } else {
    func.displayName = `PlasmicExcursao.${nodeName}`;
  }
  return func;
}

export const PlasmicExcursao = Object.assign(
  // Top-level PlasmicExcursao renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    tumbnail: makeNodeComponent("tumbnail"),
    header: makeNodeComponent("header"),
    left: makeNodeComponent("left"),
    caption: makeNodeComponent("caption"),
    title: makeNodeComponent("title"),
    subtitle: makeNodeComponent("subtitle"),
    date: makeNodeComponent("date"),
    right: makeNodeComponent("right"),
    freeBox: makeNodeComponent("freeBox"),
    info1: makeNodeComponent("info1"),
    soldTickets: makeNodeComponent("soldTickets"),
    label: makeNodeComponent("label"),
    emptySeats: makeNodeComponent("emptySeats"),
    label2: makeNodeComponent("label2"),
    info2: makeNodeComponent("info2"),
    revenue: makeNodeComponent("revenue"),
    label3: makeNodeComponent("label3"),
    averagePrice: makeNodeComponent("averagePrice"),
    label4: makeNodeComponent("label4"),
    menu: makeNodeComponent("menu"),
    salesTab: makeNodeComponent("salesTab"),
    tabButton1: makeNodeComponent("tabButton1"),
    text: makeNodeComponent("text"),
    tripsTab: makeNodeComponent("tripsTab"),
    tabButton2: makeNodeComponent("tabButton2"),
    viagens: makeNodeComponent("viagens"),
    body: makeNodeComponent("body"),
    salesView: makeNodeComponent("salesView"),
    batches: makeNodeComponent("batches"),
    batchesHeading: makeNodeComponent("batchesHeading"),
    batchesTitle: makeNodeComponent("batchesTitle"),
    batchItem: makeNodeComponent("batchItem"),
    orders: makeNodeComponent("orders"),
    ordersHeading: makeNodeComponent("ordersHeading"),
    ordersTitle: makeNodeComponent("ordersTitle"),
    ordersTable: makeNodeComponent("ordersTable"),
    tripView: makeNodeComponent("tripView"),

    // Metadata about props expected for PlasmicExcursao
    internalVariantProps: PlasmicExcursao__VariantProps,
    internalArgProps: PlasmicExcursao__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Excursão",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicExcursao;
/* prettier-ignore-end */
